defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - s3_website.yml
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
